### ISSUE TITLE
[Network] 3주차 발표주제

### ISSUE THREAD

**Issue by oneVSchoi** [One-Two-Min/CS-Study#3]
3주차(2021.12.02 ~ 2021.12.07)에 발표할 주제 정하기

6장 -> 진민지
7장 -> 최원대
8장 -> 권민

**Comment by minkwon4** [comment]
HTTP vs HTTPS, HTTP1.0 vs HTTP1.1 발표하겠습니다.

**Comment by JinMinji** [comment]
TCP 헤더 관련 발표하겠습니다!

**Comment by oneVSchoi** [comment]
[DNS](https://one10004.tistory.com/120) 관련해서 발표할게요~
